common_cluster_name: rhdg-cluster
common_namespace: rhdg-xsite-demo
common_secret_name: other-site-sa-token
common_rhdg_expose_type: NodePort
common_rhdg_expose_port: 32222
site1_ocp_api_host: api.cluster-r929p.r929p.sandbox1367.opentlc.com
site2_ocp_api_host: api.cluster-dmvvq.dmvvq.sandbox916.opentlc.com
site1_ocp_api_url: "https://{{site1_ocp_api_host}}:6443"
site2_ocp_api_url: "https://{{site2_ocp_api_host}}:6443"
site1:
  ocp_api_key: "sha256~WVPdxoPLpaRH78tmsu9jg-TKou_X6Tr_Lhtiv-sRGeg"
  local:
    name: site1
    expose:
      type: LoadBalancer
      port: "{{ common_rhdg_expose_port }}"
  locations:
    - name: site2
      clusterName: "{{ common_cluster_name }}"
      namespace: "{{ common_namespace }}"
      url: "openshift://{{ site2_ocp_api_host }}:6443"
      secretName: "{{ common_secret_name }}"
site2:
  ocp_api_key: "sha256~U5_OBk7pD1HKOLPntbSrCffijggAAP67P8V61nYkiQs"
  local:
    name: site2
    expose:
      type: LoadBalancer
      port: "{{ common_rhdg_expose_port }}"
  locations:
    - name: site1
      clusterName: "{{ common_cluster_name }}"
      namespace: "{{ common_namespace }}"
      url: "openshift://{{ site1_ocp_api_host }}:6443"
      secretName: "{{ common_secret_name }}"
