common_cluster_name: rhdg-cluster
common_namespace: rhdg-xsite-demo
common_secret_name: other-site-sa-token
common_rhdg_expose_type: LoadBalancer
common_rhdg_expose_port: 32222
common_cache_name: http-session-cache
site1_ocp_api_host: api.ocp4.example1.com
site2_ocp_api_host: api.ocp4.example2.com
site1_ocp_api_url: "https://{{site1_ocp_api_host}}:6443"
site2_ocp_api_url: "https://{{site2_ocp_api_host}}:6443"
site1:
  ocp_api_token: "sha256~..."
  local:
    name: site1
    expose:
      type: "{{ common_rhdg_expose_type }}"
      port: "{{ common_rhdg_expose_port }}"
  locations:
    - name: site2
      clusterName: "{{ common_cluster_name }}"
      namespace: "{{ common_namespace }}"
      url: "openshift://{{ site2_ocp_api_host }}:6443"
      secretName: "{{ common_secret_name }}"
site2:
  ocp_api_token: "sha256~..."
  local:
    name: site2
    expose:
      type: "{{ common_rhdg_expose_type }}"
      port: "{{ common_rhdg_expose_port }}"
  locations:
    - name: site1
      clusterName: "{{ common_cluster_name }}"
      namespace: "{{ common_namespace }}"
      url: "openshift://{{ site1_ocp_api_host }}:6443"
      secretName: "{{ common_secret_name }}"
